### ISSUE TITLE
Support for Shadowlands?

### ISSUE THREAD

**Issue by Erythros** [nebularg/LoggerHeadLite#3]
I'm currently not seeing any support for Shadowlands dungeons.
![image](https://user-images.githubusercontent.com/2624183/101107389-dd7c8500-35da-11eb-91cd-31422017ce0e.png)

Am I doing something worng?

**Comment by nebularg** [comment]
Because it's only for raids and mythic plus :p

**Comment by Erythros** [comment]
Oh, so it will show up once the dungeons in Shadowlands open up for M+?

In my screenshot (above) I could see "normal", "heroic" and "mythic" for each dungeon in BfA. Was expecting the same for SL :)

**Comment by nebularg** [comment]
Yup, it adds things as you enter them, so you'll start seeing entries once the raid is open and the mythic+ season starts
