### ISSUE TITLE
Issue when trying to open options

### ISSUE THREAD

**Issue by RazorbackRL** [nebularg/LoggerHeadLite#6]
HI, i got an issue with LUA when i try to open options. 
![image](https://github.com/user-attachments/assets/27938598-fe4e-43c9-8065-363d27805df7)

**Comment by nebularg** [comment]
Thanks, should be fixed in https://github.com/nebularg/LoggerHeadLite/commit/2f66629455481a1caf4a352b30b4423ea669b7b7
