### ISSUE TITLE
Chat spam in TWW

### ISSUE THREAD

**Issue by Gnarfoz** [nebularg/LoggerHeadLite#7]
Apparently, some of the group events fire randomly and repeatedly in 11.0.2.
Sometimes excessively on actual group changes, sometimes without any observable group changes.

Every time, LHL spams the "combat is now being logged to ..." message, filling up chat very quickly.
I'm not sure why the "if LoggingCombat() then" check doesn't prevent this.

LoggerHead (non-lite) doesn't have this issue. I think because it bails out early if the zone hasn't changed.

Could you put in some kind of similar safeguard, until Blizzard (hopefully) fixes this?

**Comment by nebularg** [comment]
oh yea, I forgot you pinged me about that. looks like PEW spam fires on group changes now, weird

**Comment by Gnarfoz** [comment]
Cool, thanks!
